### ISSUE TITLE
Use stateless components or ES2015 classes

### ISSUE THREAD

**Issue by arunoda** [mantrajs/mantra-cli#11]
Here we use `React.createClass`  which is not recommended these days. (But not wrong)
So, we need to create React classes either as stateless components or ES2015 classes extending `React.Component`.

Stateless components should be the default. But we need to have a way to create the ES2015 classes version as well.

**Comment by sungwoncho** [comment]
Implemented by https://github.com/mantrajs/mantra-cli/commit/85864f138dd41f78d0413183e60b9b7cce98b713

Added `-k (--klass)` option for `mantra generate` to extend `React.Component` rather than using stateless component. What do you think about the naming of the option?

**Comment by arunoda** [comment]
How about using --use-class as the option. May be 'uc' as the short option

**Comment by sungwoncho** [comment]
Sounds good to me.

**Comment by arunoda** [comment]
cool.

**Comment by sungwoncho** [comment]
Fixed on [v0.3.0](https://github.com/mantrajs/mantra-cli/releases/tag/v0.3.0).
