### ISSUE TITLE
Why the Mantra CLI generator says "Welcome to Mantra 0.4.2." ?

### ISSUE THREAD

**Issue by vladejs** [mantrajs/mantra-cli#119]
## Summary of the issue
As I understand from the main repo, Mantra stopped on 0.2.0. Does it really got update to 0.4.2? Where are the changes?

## Steps to reproduce

1. step 1
2. step 2
3. ...

## Environment in which this issue happens

1. CLI version:
2. node.js version:
3. Operating system:

**Comment by macrozone** [comment]
Probably i did a misstake with the release script. I will take a look later this day

**Comment by sungwoncho** [comment]
I have removed the version info from the default home page.
