### ISSUE TITLE
Create some unit tests

### ISSUE THREAD

**Issue by arunoda** [mantrajs/mantra-cli#12]
We need to create some unit tests.
For that, write tests close to the source with a directory called `__tests__`.
For an example, see: https://github.com/kadirahq/npm-base

**Comment by sungwoncho** [comment]
I have begun writing unit tests in https://github.com/mantrajs/mantra-cli/commit/9085d0f9f9f422624148377d2f466e54cdd2765c. For now I am experimenting with different test directory structure from the one you suggested.
