### ISSUE TITLE
Do we need collections 2 by default?

### ISSUE THREAD

**Issue by arunoda** [mantrajs/mantra-cli#23]
I saw we are using collections2 by default. Do we need it by default?

**Comment by sungwoncho** [comment]
We don't _need_ it. But then again, the CLI also uses things such as FlowRouter and ReactiveDict by default. I think we can have a sensible default, and allow users to specify options to overwrite the default.

i.e. `mantra create myApp --router=flow-router --localstate=reactive-dict --schema=collection2`

Having said that, I think Collection2 is used widely enough to be included as a default. I am open to more input from the users.

**Comment by arunoda** [comment]
I think we must have FlowRouter since it's the core routing tool. 

But I suggest to add Collection2 as an add on or later.

**Comment by sungwoncho** [comment]
Yeah. Since Collection2 is not a core tool, let's exclude it from default and add an option to include it. In the near future we will have to revisit other components such as reactive-dict to decide if we need to include them by default.

**Comment by arunoda** [comment]
Oh wait. We need  reactive-dict  as well to support LocalState. I think it's better to say what's in our sample-blog-app as the defaults.

See: https://github.com/mantrajs/mantra-sample-blog-app

**Comment by sungwoncho** [comment]
Fixed in [v0.3.2](https://github.com/mantrajs/mantra-cli/blob/master/RELEASE_NOTE.md#032-march-5-2016).
