### ISSUE TITLE
Generate unit tests

### ISSUE THREAD

**Issue by adamdawkins** [mantrajs/mantra-cli#25]
Can we have the cli generate associated test files too? It's probably one of the files with the most setup. 

We could generate the outer `describe` and add a pending test that would be picked up.

As a side, is there a reason all test-related features have been left out of the CLI scaffolds? If it's a key component of the Mantra spec, shouldn't the CLI also generate these files?

**Comment by sungwoncho** [comment]
There is no good reason test is left out of the CLI; it simply hasn't been implemented yet.

I like the idea of generating a pending test. I made a new branch [test](https://github.com/mantrajs/mantra-cli/tree/test). Let's start on that branch. PR is welcomed.

We will need to modify the `create` command and the generators for 'actions', 'containers,' and 'components.' Also we need to add a way to run the tests in `package.json`. Let's follow the example on https://github.com/mantrajs/mantra-sample-blog-app.

**Comment by adamdawkins** [comment]
@sungwoncho Great, I'll try and find some time to help out with this soon

**Comment by sungwoncho** [comment]
Implemented and released in [v0.3.10](https://github.com/mantrajs/mantra-cli/blob/master/RELEASE_NOTE.md#0310-april-23-2016)
