### ISSUE TITLE
EISDIR error on mantra create 

### ISSUE THREAD

**Issue by mayankchhabra** [mantrajs/mantra-cli#30]
When I try to create a new mantra project, it throws the following error
`$ mantra create`
`create  undefined/`
`invoke  init`
`toEnd: could not append to file (code EISDIR): .meteor/packages`

**Comment by sungwoncho** [comment]
That is an incorrect usage of CLI. You need to supply the path to your new app. 

Please see the [README](https://github.com/mantrajs/mantra-cli#mantra-create-path). We should probably output a friendly error in this case. PR welcomed.

**Comment by mayankchhabra** [comment]
Whoops, missed that. Thank you, it works now!

**Comment by mayankchhabra** [comment]
Made a PR!

**Comment by sungwoncho** [comment]
Thanks for the PR. Closing this.
