### ISSUE TITLE
Browserify error on startup

### ISSUE THREAD

**Issue by hmeissner** [mantrajs/mantra-cli#32]
I'm getting this error thrown after a clean `mantra create sampleapp` and running `meteor` inside of it.

```
While processing files with cosmos:browserify (for target web.browser):
   packages/kadira:flow-router/client.browserify.js: Arguments to path.resolve
   must be strings

   Browserify options:
   >  undefined
```

This just only started happening after the latest CLI update

**Comment by sungwoncho** [comment]
We upgraded Meteor to 1.3-beta.16 on 0.3.4 ([see release note](https://github.com/mantrajs/mantra-cli/blob/master/RELEASE_NOTE.md#034-march-11-2016)), and there is an issue with this Meteor version.

See https://github.com/meteor/meteor/issues/6449 for more info and a way to resolve this

**Comment by DennisKo** [comment]
I am getting something similiar.

```
=> Errors prevented startup:

   While processing files with cosmos:browserify (for target web.browser):
   packages/kadira:flow-router/client.browserify.js: Cannot read property '0' of undefined

   Browserify options:
   >  undefined
```

The solutions in [meteor/meteor#6449 ](https://github.com/meteor/meteor/issues/6449) doesnt work for me. I installed the packages locally but cant find the line in flow-router's package.js.

**Comment by hmeissner** [comment]
In my case installing flow-router alone locally did fix the issue. What exactly are you doing?

**Comment by DennisKo** [comment]
I tried:

```
meteor add cosmos:browserify
meteor add kadira:flow-router
```

Where can I even find [this](https://github.com/kadirahq/flow-router/blob/02adb1fbbdd3eb5d9c03464c5ea4646035882e44/package.js#L65) proposed changed file?

**Comment by hmeissner** [comment]
What I propose you do, and what worked for me, is just cloning flow-router repo into your project's `/packages` folder. You won't have to mess around with editing package.js nor adding browserify in this manner (flow-router depends on it now so it's there anyways).

**Comment by PolGuixe** [comment]
I just changed meteor version to beta12. I think it is a stable-ish version.
`meteor update --release 1.3-beta.12`

**Comment by DennisKo** [comment]
@Nuffx solution worked for me but  I ran into further problems with the Meteor beta on my windows machine. Got it all working on Linux now.

**Comment by cstrat** [comment]
I have been able to fix the issue by downgrading to beta12, and then back to rc2.

The bug only seems to happen for me when I run `meteor reset`.

As long as I downgrade and upgrade after resetting it is fine.
