### ISSUE TITLE
mantra create doesn't create anything or show any logs :/

### ISSUE THREAD

**Issue by sakulstra** [mantrajs/mantra-cli#35]
Seems a bit like #34, but I have meteor installed, so this can't be the problem :/
When running "mentra create test" the console promts:

```
  create  test/
  invoke  init
```

and nothing happens any more.
The folders remain empty...

I'm Running:
➜ npm -v
3.7.3
➜  node -v
v5.8.0
If this matters.

Regards and thanks for your help,
lukas

**Comment by sakulstra** [comment]
damn sry never mind... it just needed a long time due to the 1.3 beta download.
Perhaps one could have some indicator, that the process is still doing sth or just don't make it silent ;)
Regards,
Lukas

**Comment by sungwoncho** [comment]
Right now the STDOUT from scripts is silenced. I think we could have a verbose mode.

```
mantra create myApp --verbose
```

I think this is quite simple to implement. We need to add a option in `cli.js` and make `{slient: false}` conditional for shelljs in `create.js`. Would you like to do a PR?

**Comment by sakulstra** [comment]
I could but someone else was faster #36

**Comment by sungwoncho** [comment]
Implemented by https://github.com/mantrajs/mantra-cli/commit/055441636a8479114a1d16abfde9ca8c27440e6d.
