### ISSUE TITLE
.eslint

### ISSUE THREAD

**Issue by sakulstra** [mantrajs/mantra-cli#37]
I think it would be nice to add the .eslint file provided by mantra kickstarter and blog applications.

**Comment by sungwoncho** [comment]
That's fair. It'd be good to allow users to opt for jshint or jslint. Why do you think eslint would make a sensible default?

**Comment by sakulstra** [comment]
I think eslint is a good default as mantra and meteor 1.3 is all about es6, but I'm not strongly opinionated - never used one of the other ones.
For now my workflow would be:

```
mantrajs create testproject
```

Copy a .eslintrc and .editorconfig file from one of the mantra projects e.g. https://github.com/mantrajs/meteor-mantra-kickstarter/blob/v0.2.1/.eslintrc 

---

Which is not that big of a deal, but I think baking this into the cli would help at least some people getting started with linting and write better(more readable) code.

**Comment by sungwoncho** [comment]
Included in [v0.3.5](https://github.com/mantrajs/mantra-cli/blob/master/RELEASE_NOTE.md#035-march-15-2016).
