### ISSUE TITLE
`mantra generate method` error

### ISSUE THREAD

**Issue by fermuch** [mantrajs/mantra-cli#38]
If I use `mantra generate method approveDevice`, it shows the following:

```
  create  ./server/methods/approve_device.js
  update  ./server/methods/index.js
```

which is OK, but it appends to `server/methods/index.js` this:

```
import approveDevice from './approveDevice'; // <- here is the problem
...
export default function() {
  approveDevice();
}
```

And since the file is being written with lodashes, the import should also use the same structure.

**Comment by sungwoncho** [comment]
I recently fixed it in https://github.com/mantrajs/mantra-cli/commit/9dc97fa494a0b5a867f059ec350ed2d83b0c6461. Will release the patch soon along with other fixes.

**Comment by fermuch** [comment]
Nice. Didn't know about `_.snakeCase`

**Comment by sungwoncho** [comment]
Actually, the fix was something else. See the above commit.
