### ISSUE TITLE
Republish with comma fix

### ISSUE THREAD

**Issue by merlinstardust** [mantrajs/mantra-cli#44]
Can you republish the package to include the comma fix?

It's a bit annoying right now to run `mantra create`, wait for it finish, fail on `npm install`, delete the comma, and then re-run `npm install`

**Comment by sungwoncho** [comment]
Released [v0.3.6](https://github.com/mantrajs/mantra-cli/blob/master/RELEASE_NOTE.md#036-march-20-2016) with the fix. Was trying to release with other bug fixes but I have become too busy with other stuff. 

_Incidentally, this project needs more maintainers._

**Comment by merlinstardust** [comment]
Thanks for the quick publish / fix! Much appreciated
