### ISSUE TITLE
upgrade to Meteor 1.3

### ISSUE THREAD

**Issue by sungwoncho** [mantrajs/mantra-cli#46]
1.3 is officially out and we need to bump the meteor version.

**Comment by andreyantipov** [comment]
PR #45 for 1.3

Want to prose idea to create `mantra update` command, which will bring minor updates for project  (meteor-platform and npm dependencies.)

**Comment by sungwoncho** [comment]
Fixed by https://github.com/mantrajs/mantra-cli/pull/47
