### ISSUE TITLE
why mantra don't use folder 'imports' ?

### ISSUE THREAD

**Issue by mrphu3074** [mantrajs/mantra-cli#49]
http://guide.meteor.com/v1.3/structure.html#structuring-imports

Meteor 1.3 support folder 'imports' for lazy loading, but Mantra and Mantra CLI still keep files and folders in old structure.

**Comment by sungwoncho** [comment]
Please see https://github.com/kadirahq/mantra/issues/39. I think the best place for a question is the official forum https://talk.mantrajs.com/. Let's discuss further over there.
