### ISSUE TITLE
About the ESLint version

### ISSUE THREAD

**Issue by haizi-zh** [mantrajs/mantra-cli#53]
I've noticed that by default mantra cli created a project with an old-version ESLint:

```
"eslint": "1.10.x"
```

I'm wondering if there is a particular reason for which not to use ESLint 2.x?

**Comment by sungwoncho** [comment]
`package.json` was taken from [Mantra sample blog app](https://github.com/mantrajs/mantra-sample-blog-app/blob/master/package.json). I think we should bump the version and update any deprecated rules in `.eslintrc`. Would you like to help?

**Comment by haizi-zh** [comment]
That'll be great if we review the rules and make them up-to-date. I'd like to help!

**Comment by sungwoncho** [comment]
Thanks. Please make a PR when you get a chance.
