### ISSUE TITLE
constructor should be added to React components

### ISSUE THREAD

**Issue by sungwoncho** [mantrajs/mantra-cli#57]
```
  constructor(props) {
    super(props);
  }
```

should be added to a components generated using `-c` options.

**Comment by tenrocket** [comment]
Was wondering about this myself.

**Comment by sungwoncho** [comment]
@tenrocket would you like to do a PR? I think it is as simple as adding those lines to [this file](https://github.com/mantrajs/mantra-cli/blob/master/templates/client/modules/core/components/generic_class.tt).
