### ISSUE TITLE
Generating components, 2 possible results

### ISSUE THREAD

**Issue by myyellowshoe** [mantrajs/mantra-cli#59]
I noticed 2 ways components are built one way depending on how you generate them. I'm still a newb in this area I'll completely admit that, so there might be a perfectly good reason for this discrepancy. If its the case why is that? 
Whats the benefit of using one way over the other?

**mantra g component core:messages**

```
class Messages extends React.Component {
  render() {
    return (
      <div>
        Messages
      </div>
    );
  }
}

```

vs

**mantra g container core:messages**
_Generates container and following component_

```
const Messages = () => (
  <div>
    Messages
  </div>
);
```

**Comment by sungwoncho** [comment]
Contrary to your description, both `mantra g component core:messages` and `mantra g container core:messages` will generate a component looking like the following:

``` jsx
import React from 'react';

const Messages = () => (
  <div>
    Messages
  </div>
);

export default Messages;
```

To generate the component of the first form in your question, you need to use `--use-class` option. See [README](https://github.com/mantrajs/mantra-cli#mantra-generate-type-name).

The distinction between the two types of components is whether they have states or not. The first may have states while the latter cannot. Avoiding the first when you can is considered a good practice. You can read more [here](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components).

**Comment by sungwoncho** [comment]
Please re-open if there is an issue. A good place to discuss Mantra related topics is https://talk.mantrajs.com/.

**Comment by myyellowshoe** [comment]
Snap. You're right. My bad on that.
Appreciate the link I'll check that out.
