### ISSUE TITLE
Error on Generate Collection?

### ISSUE THREAD

**Issue by VikR0001** [mantrajs/mantra-cli#61]
I ran these commands:

```
mantra g module job_specialties
mantra g publication job_specialties
mantra g method job_specialties
mantra g container job_specialties:job_specialties_list
mantra g container job_specialties:new_job_specialty
mantra g action job_specialties:job_specialties
mantra g collection job_specialties -s collection2
```

Everything went perfectly until the last command:

`mantra g collection job_specialties -s collection2`

That command generated the following error:

> fs.js:549
>   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
>                  ^
> 
> Error: ENOENT: no such file or directory, open './lib/collections/job_specialties.js'

How can I correct this?

Thanks in advance for the info!

**Comment by sungwoncho** [comment]
I created a new Mantra app with CLI v0.3.9, ran all the commands in series, but failed to reproduce the error. What version of CLI and Meteor are you using? More information needed.

**Comment by VikR0001** [comment]
Interesting.  The project is METEOR@1.3.1, and mantra-cli@0.3.9.

**Comment by sungwoncho** [comment]
I just deleted `/lib` from the app and ran `mantra g collection job_specialties -s collection2` to successfully reproduce your error. The problem seems to be that there is no directory for the collection. Did you change the directory structure? Please make sure `/lib/collections` exists in your app.

**Comment by VikR0001** [comment]
Makes sense. Thanks very much!

**Comment by VikR0001** [comment]
That was definitely it. I have started a new project directory for my app, built from the ground up using Mantra-CLI.
