### ISSUE TITLE
Set tab sizes

### ISSUE THREAD

**Issue by mbabauer** [mantrajs/mantra-cli#69]
Is there a way to configure mantra-cli to set the desired tab sizes?  It defaults to 2 spaces, but I prefer 4 spaces.

**Comment by sungwoncho** [comment]
Currently there is no way to configure the behavior of the CLI. There has been a discussion on introducing `.mantrarc` or `.mantra` directory for custom behavior. See [here](https://github.com/mantrajs/mantra-cli/issues/3#issuecomment-203417110). What do you think?

**Comment by mbabauer** [comment]
I made a comment over on the other ticket.  I think having a .rc of config folder is a wonderful idea.

**Comment by sungwoncho** [comment]
I started working on configuration on [config](https://github.com/mantrajs/mantra-cli/tree/config) branch.

The idea is to generate `.mantra/config.json` when a new app is created. Currently `config.json` is:

``` json
{
  "tabSpace": 2
}
```

Before we write a template, we replace spaces according to the `tabSpace` in the config. ([here](https://github.com/mantrajs/mantra-cli/commit/bd3233a28e71fb4d468a29145f459711a23f202a#diff-a154dfc9a20b2e49e7bef49887c05d7dR296))

Some issues:
- How can we customize tab spaces for `mantra create`?
- How can existing projects migrate to this new version? Maybe we can have `mantra restore config` to generate/overwrite the `.mantra/config.json`? ([here](https://github.com/mantrajs/mantra-cli/commit/508a65b0268aaf627fb537ec26df1aea7e10faaa))

**Comment by macrozone** [comment]
I think this is resolved with the mantra-cli.yaml ?

**Comment by sungwoncho** [comment]
@macrozone you are right. Closing.
