### ISSUE TITLE
should throw an error if the component name is invalid

### ISSUE THREAD

**Issue by fermuch** [mantrajs/mantra-cli#75]
I accidentally wrote this:

```
$ mantra g component travels::distanceTraveled
  create  ./client/modules/core/components/.jsx
  create  ./client/modules/core/components/tests/.js
```

It should throw an error instead of creating files without a name.

**Comment by sungwoncho** [comment]
To get names for module and entity, we use this code: `let [moduleName, entityName] = name.split(':');` (see [here](https://github.com/mantrajs/mantra-cli/blob/master/lib/generators/component.js#L7)).

I have a suggestion: we can do length check on `name.split(':')` and return false while validating. https://github.com/mantrajs/mantra-cli/blob/master/lib/commands/generate.js#L32-L45

Would you like to do a PR? Should be a quick one.
