### ISSUE TITLE
Sanitize template variable

### ISSUE THREAD

**Issue by sungwoncho** [mantrajs/mantra-cli#9]
```
mantra g component foo:header.menu
```

Results in:

``` js
import React from 'react';

const Header.Menu = React.createClass({
  render() {
...
```

Note `Header.Menu` on line 3.

_Related_

```
mantra g component foo:header_menu
```

Results in:

``` js
import React from 'react';

const Header_menu = React.createClass({
  render() {
    return (
...
```

**Comment by arunoda** [comment]
@sungwoncho It's better to throw an error here if there is a dot.
- We need to use camelcase for variable/class naming.
- We can use underscore for file names.

So, following command,

```
mantra g component foo:headerMenu
```

will generate two the file as:

```
app/module/foo/components/header_menu.jsx
```

And the component will be:

``` js
import React from 'react';
const HeaderMenu = () => (
  <div></div>
);

export default HeaderMenu;
```

**Comment by sungwoncho** [comment]
Fixed on [v0.3.0](https://github.com/mantrajs/mantra-cli/releases/tag/v0.3.0).

**Comment by sungwoncho** [comment]
@arunoda i found that Mantra spec still uses file names with dots in them. For instance, see [here](https://kadirahq.github.io/mantra/#sec-components). Is this outdated? Happy to submit a PR.

**Comment by arunoda** [comment]
It seems like it's outdated. Yeah. send me a PR :)
