### ISSUE TITLE
CLI deleted all my modules!

### ISSUE THREAD

**Issue by kjetilge** [mantrajs/mantra-cli#91]
I accidentally hit the enter button when the terminal showed this:

```
mantra d modul
```

Then all my modules disappeared!

**Comment by sungwoncho** [comment]
Wow. That sounds like a serious bug. Hope you didn't lose much work. I will investigate this weekend. Meanwhile, @macrozone do you have any clues?

**Comment by macrozone** [comment]
@sungwoncho: i fixed it in a PR, but i did not made a release. Could you review the to PRs and make a new release?

**Comment by sungwoncho** [comment]
Released the fix in `0.4.0`. Thanks everyone.
